### ISSUE TITLE
NPE in Language Server

### ISSUE THREAD

**Issue by eNBeWe** [kieler/osgiviz#24]
Hi,
I am currently trying to render some images on a server, using klighd-linux as well as the nightly osgiviz language server.

I see lots of NPE in the console log of klighd-linux:
```
Language Server Server:         at de.cau.cs.kieler.osgiviz.OsgiVizFileHandler.storeLayoutOptions(OsgiVizFileHandler.java:265)
        at de.cau.cs.kieler.osgiviz.OsgiVizFileHandler.writeCurrentModelToFile(OsgiVizFileHandler.java:184)
        at de.cau.cs.kieler.osgiviz.actions.AbstractVisualizationContextChangingAction.execute(AbstractVisualizationContextChangingAction.java:74)
        at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.handle(KGraphDiagramServer.java:668)
        at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.accept(KGraphDiagramServer.java:330)
        at org.eclipse.sprotty.DefaultDiagramServer.accept(DefaultDiagramServer.java:40)
        at org.eclipse.sprotty.xtext.ls.DiagramLanguageServer.accept(DiagramLanguageServer.java:130)
        at de.cau.cs.kieler.klighd.lsp.KGraphLanguageServerExtension.accept(KGraphLanguageServerExtension.java:195)
        at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
        at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:68)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
```

**Comment by NiklasRentzCAU** [comment]
This is a known issue that happens when trying to store the currently configured visualization contexts in plain Java applications, as we try to store the layout options, which is currently not supported by ELK in plain Java, see [their issue 719](https://github.com/eclipse/elk/issues/719).
This NPE is caught and just logged but does no harm. I can however remove and replace it with just a message that saving the layout options failed because it is executed outside of Eclipse.
